" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

"------------------------------------------------------------------------------
" General Config
"------------------------------------------------------------------------------

set relativenumber              " Relative numbers are good for movements
set number                      " Abs numbers are good for location in file
set backspace=indent,eol,start  " Allow backspace in insert mode
set history=1000                " Store lots of :cmdline history
set showcmd                     " Show incomplete cmds down the bottom
set showmode                    " Show current mode down the bottom
set gcr=a:blinkon0              " Disable cursor blink
set visualbell                  " No sounds
set belloff=all
set autoread                    " Reload files changed outside vim
set ruler                       " Its good to know your position
set showmatch                   " set show matching parenthesis
set mat=5                       " duration to show paren match 1/10 sec


" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

"turn on syntax highlighting
syntax on

"------------------------------------------------------------------------------
" Key Mappings
"------------------------------------------------------------------------------

" Change the <leader> to something more reachable
" The mapleader has to be set before vundle starts loading all
" the plugins.
let mapleader = ","

" ESC is too far away!
imap jj <Esc>

"------------------------------------------------------------------------------
" vim-plug Initialization
"------------------------------------------------------------------------------

call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'jeffkreeftmeijer/vim-numbertoggle'
Plug 'sheerun/vim-polyglot'
Plug 'rakr/vim-one'
Plug 'ntpeters/vim-better-whitespace'
Plug 'pangloss/vim-javascript'
Plug 'leafgarland/typescript-vim'
Plug 'maxmellon/vim-jsx-pretty'
Plug 'jparise/vim-graphql'
Plug 'jasdel/vim-smithy'

Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-git'
Plug 'christoomey/vim-tmux-navigator'
Plug 'preservim/nerdtree'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'rust-lang/rust.vim'
Plug 'jclsn/glow.vim'

call plug#end()

"------------------------------------------------------------------------------
" Turn Off Swap Files
"------------------------------------------------------------------------------

set noswapfile    " NOTE: Maybe this isn't a good idea? We'll see if it bites me
set nobackup
set nowb

"------------------------------------------------------------------------------
" Indentation
"------------------------------------------------------------------------------

filetype plugin on
filetype indent on

set tabstop=2
set shiftwidth=2
set expandtab

" Display tabs and trailing spaces visually
set list listchars=tab:\ \ ,trail:·

set nowrap       " Don't wrap lines
set linebreak    " Wrap lines at convenient points

"------------------------------------------------------------------------------
" Folds
"------------------------------------------------------------------------------

set foldmethod=indent   " fold based on indent
set foldnestmax=3       " deepest fold is 3 levels
set nofoldenable        " dont fold by default

"------------------------------------------------------------------------------
" Completion
"------------------------------------------------------------------------------

set wildmode=list:longest
set wildmenu                   " enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~    " stuff to ignore when tab completing
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=*DS_Store*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif

"------------------------------------------------------------------------------
" Scrolling
"------------------------------------------------------------------------------

set scrolloff=8           " Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

"------------------------------------------------------------------------------
" Search
"------------------------------------------------------------------------------

set incsearch       " Find the next match as we type the search
set hlsearch        " Highlight searches by default
set ignorecase      " Ignore case when searching...
set smartcase       " ...unless we type a capital

"------------------------------------------------------------------------------
" Plugin Settings
"------------------------------------------------------------------------------
" Plugin specific settings by name

so ~/.dotfiles/vim/settings.vim

"------------------------------------------------------------------------------
" Experimental Settings
"------------------------------------------------------------------------------
" These settings are ignored by VCS and meant as a sandbox to try new things

"so ~/.dotfiles/vim/extras.vim
